####################################################
# installArgoCD enable true will install argo-cd,argo-rollouts,argo-workflows,argo-events,argocd-image-updater
installArgoCD: false

# installArgoRollouts enable true will install argo-rollouts
installArgoRollouts: true

########################################################################################
## Info related to registry where OEA images are stored
imageCredentials:
  repoUrl: https://quay.io/
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: quay.io/opsmxpublic

#######################################################################################
# If installed ArgoCD set to true it will installdemoapps
# Set to false if no applications to be displayed in ArgoCD as part of default installation
installdemoapps: false
#######################################################################################
# Set to true if ISD needs to connect to ArgoCD using agent service
autoconfigureagent: false
#######################################################################################
# Global Configuration
######################

global:
  # Custom Images registry where all the OSS and customized images used in the helm chart are stored
  # Only update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  customImages:
    registry: quay.io/opsmxpublic
  # when this flag is set to false; UI will be accessible over http instead of https
  ssl:
    enabled: true

  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  # Else, the TLS secrets will need to created manually
  certManager:
    installed: true

  createIngress: true

  oesUI:
    host: ISD.REPLACE.THIS.WITH.YOURCOMPANY.COM

  keycloak:
    enabled: false
    host: oes.example.ops.com

  minio:
    enabled: true

  argorollouts:
    #specify the argorollouts url like argorollouts.ninja-test.opsmx.net
    host: "ROLLOUTS.REPLACE.THIS.WITH.YOURCOMPANY.COM"

  ###############################################################################
  # Set it to false if own LDAP is to be configured
  installOpenLdap: true

  ## ldap configuration used for authentication and authorization
  ldap:
    enabled: true
    url: ldap://openldap:389
    managerDn: cn=admin,dc=example,dc=org
    managerPassword: opsmxadmin123
    groupSearchBase: ou=groups,dc=example,dc=org
    groupSearchFilter: member={0}
    groupRoleAttributes: cn
    userDnPattern: cn={0},dc=example,dc=org

argo-rollouts:
  # Default set to true . Set to false if crds already exists in the cluster instead of deleting the CRDs
  installCRDs: true
  #Set to false if crds to be deleted as part of helm uninstall
  keepCRDs: true

#######################################################################################################################
# Values of OEA Database
db:
  ## Set it to false if any external database is to be used
  enabled: true
  url: jdbc:postgresql://oes-db:5432
  username: postgres
  password: networks123

###################################
forwarder:
  enabled: true
################################################################################################
## Redis configuration
## Set it to false only if OES needs to be configured with external redis
installRedis: true
##########################################################################
