####################################################
# installArgoCD enable true will install argo-cd,argo-rollouts,argo-workflows,argo-events,argocd-image-updater
installArgoCD: false

# installArgoRollouts enable true will install argo-rollouts
installArgoRollouts: true
###########################################################################################
#  OEA-AP Install OEA and Argo Services . Change to None if only Argo Services to be installed.
installationMode: None

######################
global:
  # when this flag is set to false; UI will be accessible over http instead of https
  ssl:
    enabled: true

  # Else, the TLS secrets will need to created manually
  certManager:
    installed: true

  createIngress: true

  minio:
    enabled: false

  argorollouts:
    host: "rollouts.ryzon7-argo22.opsmx.org"

  oesUI:
    host: sai.isd.ninja-test.opsmx.net

  ###############################################################################
  # Set it to false if own LDAP is to be configured
  installOpenLdap: false

  ## ldap configuration used for authentication and authorization
  ldap:
    enabled: false

###################################################
# argo-rollouts configuration
#######################

argo-rollouts:
  # Default set to true . Set to false if crds already exists in the cluster instead of deleting the CRDs
  installCRDs: true
  #Set to false if crds to be deleted as part of helm uninstall
  keepCRDs: false
#######################################################################################################################
# Values of OEA Database
db:
  enabled: false
###############################################################################################################################
forwarder:
  enabled: false
################################################################################################
## Redis configuration
## Set it to false only if OES needs to be configured with external redis
installRedis: false
##########################################################################
####################################################
auditClient:
  image:
    repository: ubi8-oes-audit-client
    tag: v4.1.1-rc2
###################################################
gate:
  image:
    repository: ubi8-gate
    tag: v4.1.1-rc2
##################################################
sapor:
  image:
    repository: ubi8-oes-sapor
    tag: v4.1.1-rc2
###################################################
platform:
  image:
    repository: ubi8-oes-platform
    tag: v4.1.1-rc2
###################################################
autopilot:
  image:
    repository: ubi8-oes-autopilot
    tag: v4.1.1-rc2
###################################################
ui:
  image:
    repository: ubi8-oes-ui
    tag: v4.1.1-rc2
###################################################
dashboard:
  image:
    repository: ubi8-oes-dashboard
    tag: v4.1.1-rc2
#####################################################
datascience:
  image:
    repository: ubi8-oes-datascience
    tag: v4.1.1-rc2
#####################################################
audit:
  image:
    repository: ubi8-oes-audit-service
    tag: v4.1.1-rc2
######################################################
visibility:
  image:
    repository: ubi8-oes-visibility
    tag: v4.1.1-rc2
