{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oea
    component: gate
{{ include "oea.standard-labels" . | indent 4 }}
{{- if .Values.gate.serviceAnnotations }}
  annotations:
{{ toYaml .Values.gate.serviceAnnotations | indent 4 }}
{{- end }}
  name: oea-gate
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: "https"
    port: 443
    targetPort: 8084
  - name: "oea-gate-service"
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: "http"
    port: 80
    targetPort: 8084
  selector:
    app: oea
    component: gate
{{- end -}}
