{{- if and (.Values.installArgoCD) (.Values.autoconfigurecarina) }}
argos:
  - name: oesargo
    url: https://{{ .Values.global.argocd.host }}
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{{- end }}
httpListenPort: 8090
controller:
  url: 'https://opsmx-controller-controller1:9003'
  caPath: /app/secrets/controller-ca.crt
  certificatePath: /app/secrets/controller-control/tls.crt
  keyPath: /app/secrets/controller-control/tls.key
  updateFrequencySeconds: 30
databases:
  audit:
    type: postgresql
    connectString: host=oes-db  user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=auditdb
  platform:
    type: postgresql
    connectString: host=oes-db user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=platformdb
