{{- if (eq .Values.installationMode "OEA-AP") }}
{{- if or (.Values.installArgoRollouts) (.Values.installArgoCD) }}
apiVersion: v1
kind: Secret
metadata:
  name: opsmx-profile
stringData:
  {{- if .Values.installArgoCD }}
  cd-integration: "true"
  {{- else }}
  cd-integration: "false"
  {{- end }}
  source-name: "argocd" 
  gate-url: "{{ .Values.global.oesUI.protocol }}://{{ .Values.global.oesUI.host }}"
  user: "admin"
{{- end }}
{{- end }}
