{{- if (eq .Values.installationMode "OEA-AP") }}
apiVersion: v1
data:
  feature.yml: |
     feature:
       auth-provider:
         flag: true
         jira: OP-18050
kind: ConfigMap
metadata:
  labels:
    app: oes
  name: isd-feature-flag-config
{{- end }}
