{{- if and (.Values.installArgoCD) (.Values.installdemoapps) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "10"
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: {{ .Release.Namespace }}
    server: ''
  source:
    path: sampleapps
    repoURL: 'git@github.com:OpsMx/argo-sample-apps.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
{{- end -}}
