{{- if and (.Values.global.certManager.installed) (eq .Values.installationMode "OEA-AP") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Namespace }}-oea
spec:
  acme:
    email: srinivas@opsmx.io
    preferredChain: ""
    privateKeySecretRef:
      name: demo-authtls
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
