{{- if and (eq .Values.installationMode "OEA-AP") (.Values.installArgoCD) -}}
{{- if or .Values.autoconfigurecarina .Values.autoconfigureagent .Release.IsInstall -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oes-autoconfigure
  labels:
{{ include "oes.standard-labels" . | indent 4 }}
data:
  datasource-api.sh: |-
    #!/bin/bash
    #set -x
    echo \"Waiting for all Argo Server  to come-up\"
    wait_period=0
    while true
    do
    ## install argoCLI
    curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    chmod +x /usr/local/bin/argocd

    {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
    status="$(curl -Is https://{{ .Values.global.argocd.host }} | head -1)"
    validate=$(echo $status | awk '{print $2}')
    {{- else }}
    {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
    status="$(curl -Is http://{{ .Values.global.argocd.host }} | head -1)"
    validate=$(echo $status | awk '{print $2}')
    {{- else }}
    validate=$(echo "200")
    {{- end }}
    {{- end }}

    kubectl get po -n {{ .Release.Namespace }} -o jsonpath='{range .items[*]}{..metadata.name}{"\t"}{..containerStatuses..ready}{"\n"}{end}' > /tmp/live.status
    ARGOCDSERVER=$(grep argocd-server /tmp/live.status |grep -v deck | awk '{print $2}')
    wait_period=$(($wait_period+10))
    if   [ "$ARGOCDSERVER" == "true" ] && [ "$validate" == "200" ];
    then
      echo \"ArgocdServer is  Up and Ready..\"
      while true
      do
      ## get the user password
      argopassword=$(kubectl get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)

      ##argocli login
      {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
      argocd login {{ .Values.global.argocd.host }} --username=admin --password=$argopassword --grpc-web
      {{- else }}
      {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
      argocd login {{ .Values.global.argocd.host }} --username=admin --password=$argopassword --grpc-web --insecure
      {{- else }}
      argocd login --insecure --port-forward --port-forward-namespace=opsmx-argo --plaintext --username=admin --password=$argopassword
      {{- end }}
      {{- end }}


      {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
      token=$(argocd account generate-token)
      {{- else }}
      {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
      token=$(argocd account generate-token --insecure)
      {{- else }}
      token=$(argocd account generate-token --insecure --port-forward --port-forward-namespace=opsmx-argo)
      {{- end }}
      {{- end }}
      wait=0
      if [ -z $token ]
      then
        wait=$(($wait+10))
        if [ $wait -gt 2000 ];
        then
          echo \"Script is timed out Admin Secret not found .......\"
          break
        else
          echo \"Waiting to get the admin token\"
          sleep 1m
        fi

      else
         encodedtoken=$(echo -n $token | base64 -w0)
         {{- if .Values.autoconfigurecarina -}}
         ## autoconfiguration for carina with isd
         ## replace the secret
         kubectl get secret oes-carina-config -o jsonpath='{.data.*}' | base64 -d > carina-secret.yaml
         yq e '.argos.[].token = "'$encodedtoken'"' carina-secret.yaml > carina-manager.yaml
         kubectl delete secret oes-carina-config
         kubectl create secret generic oes-carina-config  --from-file=carina-manager.yaml
         kubectl delete  po -l component=carina
         {{- end -}}
         {{- if .Values.autoconfigureagent -}}
         ##Configure the Agent to the ISD
         #Create Agent in the ISD-UI via API
         curl --location --request POST 'http://oes-sapor:8085/oes/accountsConfig/v3/agents?cdType=Argo' --header 'Content-Type: application/json' --header 'x-spinnaker-user: admin'  --data-raw '{"agentName":"isd-argo-agent","description":"default isd-argo"}'
         curl --location --request GET 'http://oes-sapor:8085/oes/accountsConfig/agents/isd-argo-agent/manifest' --header 'x-spinnaker-user: admin' > /tmp/manifest.yaml
         cd /tmp/
         wget https://github.com/patrickdappollonio/kubectl-slice/releases/download/v1.2.3/kubectl-slice_1.2.3_linux_x86_64.tar.gz
         tar -xvf /tmp/kubectl-slice_1.2.3_linux_x86_64.tar.gz
         cp /tmp/kubectl-slice /usr/local/bin/
         mkdir /tmp/yamls
         kubectl-slice --input-file=/tmp/manifest.yaml --output-dir=/tmp/yamls/.
         yq e -i '.subjects[0].namespace = "{{ .Release.Namespace }}"' /tmp/yamls/clusterrolebinding-opsmx-agent-isd-argo-agent.yaml
         kubectl apply -f /tmp/yamls/
         {{- end -}}
         break
      fi
      done
      break
    else
      if [ $wait_period -gt 2000 ];
      then
       echo \"Script is timed out as the Argocd Server is not ready yet.......\"
       break
      else
       echo \"Waiting for  Argocd Server to be ready\"
       sleep 1m
      fi
    fi
    done
{{- end -}}
{{- end -}}
