{{- if and (eq .Values.installationMode "OEA-AP") (.Values.installArgoCD) -}}
{{- if or .Values.autoconfigurecarina .Values.autoconfigureagent .Release.IsInstall -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oes-auto-configure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oes-auto-configure
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - pods/portforward
  verbs:
  - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server-extensions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oes-auto-configure
subjects:
- kind: ServiceAccount
  name: oes-auto-configure
{{- end }}
{{- end }}
