{{- if and (eq .Values.installationMode "OEA-AP") (.Values.installArgoCD) -}}
{{- if or .Values.autoconfigurecarina .Values.autoconfigureagent -}}
{{- if .Release.IsInstall -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oes-auto-configure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oes-auto-configure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: oes-auto-configure
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
