{{- if and (eq .Values.installationMode "OEA-AP") (.Values.installArgoCD) -}}
{{- if and .Values.autoconfigurecarina .Release.IsInstall -}}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "5"
  labels:
    app: oea
{{ include "oea.standard-labels" . | indent 4 }}
  name: oea-autoconfig
spec:
  template:
    metadata:
      labels:
        app: oea
{{ include "oea.standard-labels" . | indent 8 }}
    spec:
      serviceAccountName: argocd-server
      containers:
      - command: ["sh", "/tmp/config/datasource-api.sh" ]
        name: carina-auto-configure
        image: {{ .Values.global.customImages.registry }}/awsgit:v2-openssh-javalibs
        volumeMounts:
        - mountPath: /tmp/config
          name: carina-autoconfigure
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      restartPolicy: OnFailure
      volumes:
      - configMap:
          defaultMode: 420
          name: oea-carina-autoconfigure
        name: carina-autoconfigure
{{- end -}}
{{- end -}}
