{{- if .Values.installkeycloak }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: opsmx-init
          image: opsmx11/java:keycloak
          imagePullPolicy: Always
          command:
          - sh
          - -c
          - |
            echo 'Loading OpsMx theam...'
            cp -r /tmp/OpsMx/ /opt/keycloak/themes/OpsMx
          volumeMounts:
          - mountPath: /opt/keycloak/themes/
            name: opsmx
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:20.0.2
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "keycloak"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "keycloak123"
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        volumeMounts:
        - mountPath: /opt/keycloak/themes/
          name: opsmx
      volumes:
      - emptyDir: {}
        name: opsmx
{{- end }}
