{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oea
    component: platform
{{ include "oea.standard-labels" . | indent 4 }}
{{- if .Values.platform.serviceAnnotations }}
  annotations:
{{ toYaml .Values.platform.serviceAnnotations | indent 4 }}
{{- end }}
  name: oea-platform
spec:
  type: ClusterIP
  ports:
  - name: oea-platform
    protocol: TCP
    port: 8095
    targetPort: 8095
  selector:
    app: oea
    component: platform
{{- end -}}
