{{- if (eq .Values.secretStore "db") }}
spring:
  datasource:
    url: {{ .Values.db.url }}/platformdb
    username: '{{ .Values.db.username }}'
    password: '{{ .Values.db.password }}'
ldap.managerPassword: '{{ .Values.global.ldap.managerPassword }}'
redis:
    connection: {{ template "oea.redisBaseURL" . }}
#datasource.url: {{ .Values.db.url }}/visibilitydb
#postgres.password: '{{ .Values.db.password }}'
#postgres.username: '{{ .Values.db.username }}'
{{- end }}

datasource:
  secretManagement:
    source: {{ .Values.secretStore }}
rbacEnabled: false
supportedFeatures:
{{ toYaml .Values.platform.config.supportedFeatures | indent 2 }}
userGroup:
  superAdminGroups: {{ .Values.global.saporgate.config.adminGroups }}
fixedDelay:
  in:
    milliseconds: 120000
initialDelay:
  in:
    milliseconds: 300000
scheduler:
  workerThreads: 50
user:
  {{- if .Values.gate.config.saml.enabled }}
  source: {{ .Values.gate.config.saml.userSource }}
  {{- else }}
  source: {{ .Values.platform.config.userSource }}
  {{- end }}
ldap:
  enabled: {{ .Values.global.ldap.enabled }}
  url: {{ tpl .Values.global.ldap.url . }}
  managerDn: {{ .Values.global.ldap.managerDn }}
  groupSearchBase: {{ .Values.global.ldap.groupSearchBase }}
  groupSearchFilter: {{ .Values.global.ldap.groupSearchFilter }}
  groupRoleAttributes: {{ .Values.global.ldap.groupRoleAttributes }}
  userDnPattern: {{ .Values.global.ldap.userDnPattern }}

oes:
  sapor:
    url: http://oea-sapor:8085
  autopilot:
    url: http://oea-autopilot:8090
  dashboard:
    url: http://oea-dashboard:8094
  visibility:
    url: http://oea-visibility:8096
  auditclient:
    url: http://oea-audit-client:8098
  policyGate:
    url: "{{ .Values.global.oeaUI.protocol }}://{{ .Values.global.oeaUI.host }}/gate"
    path: /v1/data/
  ui:
  # Ex: "https://oea-poc.dev.opsmx.org/"
    url: "{{ .Values.global.oeaUI.protocol }}://{{ .Values.global.oeaUI.host }}/ui"
  gate:
    url: http://oea-gate:8084
  approvalGate:
    apiUrl: {{ .Values.global.oeaUI.protocol }}://{{ .Values.global.oeaUI.host }}/gate/visibilityservice/v5/approvalGates/{id}/trigger

  verificationGate:
    apiUrl: {{ .Values.global.oeaUI.protocol }}://{{ .Values.global.oeaUI.host }}/gate/autopilot/api/v3/registerCanary

logging:
  level:
    com.opsmx.platformservice: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv
argoRollout:
  {{- if and (.Values.installArgoCD) (.Values.installArgoRollouts) }}
  appAutoCreation: false
  {{- else }}
  {{- if and .Values.installArgoRollouts (not .Values.installArgoCD) }}
  appAutoCreation: true
  {{- end }}
  {{- end }}
