{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oea
    component: visibility 
{{ include "oea.standard-labels" . | indent 4 }}
{{- if .Values.visibility.serviceAnnotations }}
  annotations:
{{ toYaml .Values.visibility.serviceAnnotations | indent 4 }}
{{- end }}
  name: oea-visibility
spec:
  type: ClusterIP
  ports:
  - name: visibility 
    protocol: TCP
    port: 8096
    targetPort: 8096
  selector:
    app: oea
    component: visibility
{{- end -}}
