{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oea
    component: auditclient
{{ include "oea.standard-labels" . | indent 4 }}
{{- if .Values.auditClient.serviceAnnotations }}
  annotations:
{{ toYaml .Values.auditClient.serviceAnnotations | indent 4 }}
{{- end }}
  name: oea-audit-client
spec:
  ports:
  - name: auditclient
    port: 8098
    protocol: TCP
    targetPort: 8098
  selector:
    app: oea
    component: auditclient
  type: ClusterIP
{{- end -}}
