{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oea
    component: db
{{ include "oea.standard-labels" . | indent 4 }}
{{- if .Values.db.serviceAnnotations }}
  annotations:
{{ toYaml .Values.db.serviceAnnotations | indent 4 }}
{{- end }}
  name: oea-db
spec:
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: oea
    component: db
{{- end -}}
