spring:
  datasource:
{{- if (eq .Values.secretStore "db") }}
    url: {{ .Values.db.url }}/visibilitydb
    username: '{{ .Values.db.username }}'
    password: '{{ .Values.db.password }}'
    #sslmode: require
{{- end }}
  visiblity:
    connectors:
      configured: JIRA,GIT,AUTOPILOT,SONARQUBE,JENKINS,AQUAWAVE
  logging:
    level:  
      io:     
        swagger:
          models: 
            parameters:
              AbstractSerializableParameter: ERROR

auditservice:
  enabled: true
  name: auditservice
  url: "http://oea-audit-service:8097"
auditclientservice:
  name: auditclientservice
  url: "http://oea-audit-client:8098"

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    elasticsearch:
      enabled: false
    ldap:
      enabled: false

ui:
  approval:
    url: {{ .Values.global.oeaUI.protocol }}://{{ .Values.global.oeaUI.host }}/ui/application/visibility/{applicationId}/{serviceId}/{approvalGateId}  

gate:
  url: http://oea-gate:8084

jira:
  api:
    url: /rest/api/2/search
  navigate:
    url: hosturl/browse/{issue_Id}

git:
  apiurl: /repos/{account}/{repo}/commits/{commitId}
  userurl: /user
  navigate.url: https://github.com/{account}/{repo_name}/commit/{commit_Id}

jenkins:
  api:
    url: /job/{jobname}/{buildId}/api/json
  navigate:
    url: hosturl/job/{jobname}/{buildId}

sonar:
  navigate:
    Url: hosturl/dashboard?id={projectKey}

aquawave:
  api:
    url: https://api.aquasec.com/v2/images/{id}
  navigate:
    url: https://cloud.aquasec.com/vs/#/images/{id}

autopilot:
  api:
    url: http://oea-autopilot:8090

platform:
  service:
    url: http://oea-platform:8095

datasource:
  secretManagement:
    source: {{ .Values.secretStore }}

standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv

